apiVersion: v1
kind: Service
metadata:
  name: http-echo-poor-kubernetes-service
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: http-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo-poor-kubernetes-deployment
spec:
  selector:
    matchLabels:
      app: http-echo
  replicas: 1
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo-poor-kubernetes-image
        image: hashicorp/http-echo
        args:
        - "-text=http-echo"
        ports:
        - containerPort: 5678
